exclude: 'test.py'
fail_fast: false

repos:
  - repo: local
    hooks:
      # - id: check-repo-structure
      #   name: Check Repo Structure
      #   description: Ensure repository structure is correct.
      #   # use /bin/bash for linux
      #   entry: bash ./pre-commit/check-repo-structure.sh
      #   language: system
      #   pass_filenames: false
      - id: check-added-large-files
        name: Check Added Large Files
        description: Prevent adding large files to the repository.
        entry: check-added-large-files
        language: system
        types: [text]
        args: ['--maxkb=2048', --enforce-all]
      - id: nbstripout
        name: nbstripout
        description: Strip output from Jupyter notebooks.
        entry: nbstripout
        language: system
        files: \.ipynb$

      - id: check-ast
        name: Check AST
        description: Check Python files for AST issues.
        entry: check-ast
        language: system
        types: [python]
      - id: check-yaml
        name: Check YAML
        description: Validate YAML files.
        entry: check-yaml
        language: system
        types: [yaml]
      - id: check-json
        name: Check JSON
        description: Validate JSON files.
        entry: check-json
        language: system
        types: [json]
      - id: check-toml
        name: Check TOML
        description: Validate TOML files.
        entry: check-toml
        language: system
        types: [toml]
      # - id: check-jsonschema
      #   name: Check JSON Schema
      #   description: Validate JSON files against schema.
      #   entry: check-jsonschema
      #   language: system
      #   files: (^|/)schema\.json$
      #   args: ["--schemafile", "schemas/foo.json"]

      - id: pretty-format-json
        name: Pretty Format JSON
        description: Format JSON files.
        entry: pretty-format-json
        language: system
        types: [json]
        exclude: \.ipynb$
        args: [--autofix, --no-sort-keys, --no-ensure-ascii, --indent=2]
      - id: requirements-txt-fixer
        name: Requirements TXT Fixer
        description: Format requirements.txt files.
        entry: requirements-txt-fixer
        language: system
        files: (^|/)requirements\.txt$
      - id: isort
        name: isort
        description: Sort imports using isort.
        entry: isort
        language: system
        types: [python]
        # pass_filenames: true
        args: [--settings-path=pyproject.toml]
      - id: pyproject-fmt
        name: pyproject-fmt
        description: Format pyproject.toml files.
        entry: pyproject-fmt
        language: system
        files: (^|/)pyproject\.toml$
        # pass_filenames: false
        # require_serial: false
        # args: []
        # require_serial: false
        # additional_dependencies: []
        # minimum_pre_commit_version: '2.0.0'
      - id: end-of-file-fixer
        name: End of File Fixer
        description: Ensure files end with a newline.
        entry: end-of-file-fixer
        language: system
        types: [text]
      - id: trailing-whitespace
        name: Trailing Whitespace
        description: Remove trailing whitespace.
        entry: trailing-whitespace-fixer
        language: system
        types: [text]
      - id: black
        name: Black
        description: Format Python code using Black.
        entry: black .
        language: system
        types: [python]
        args: ['--config=pyproject.toml']
      - id: autoflake
        name: Autoflake
        description: Remove unused imports and variables using Autoflake.
        entry: autoflake
        language: system
        types: [python]
        args: [--config=pyproject.toml]

      # - id: interrogate
      #   name: Interrogate
      #   description: Check code coverage using Interrogate.
      #   entry: interrogate
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      #   args: ['--config=pyproject.toml']

      # - id: no-commit-to-branch
      #   name: No Commit to Branch
      #   description: Prevent commits to specific branches.
      #   entry: no-commit-to-branch
      #   language: system
      #   args: [--branch, develop, --branch, main, --branch, master]
      #   pass_filenames: false
      - id: detect-private-key
        name: Detect Private Key
        description: Detect private keys in files.
        entry: detect-private-key
        language: system
        types: [text]

      # - id: pytest
      #   name: Run Tests
      #   description: Run tests using pytest.
      #   entry: pytest
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      #   always_run: true
